In [1]:
# Import required libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

In [2]:
# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [3]:
df = pd.read_csv('IRIS.csv') 
print(df.shape)
df.describe().transpose()

(150, 5)


count      mean       std  min  25%   50%  75%  max
sepal_length  150.0  5.843333  0.828066  4.3  5.1  5.80  6.4  7.9
sepal_width   150.0  3.054000  0.433594  2.0  2.8  3.00  3.3  4.4
petal_length  150.0  3.758667  1.764420  1.0  1.6  4.35  5.1  6.9
petal_width   150.0  1.198667  0.763161  0.1  0.3  1.30  1.8  2.5

In [6]:
target_column = ['species'] 
predictors = list(set(list(df.columns))-set(target_column))
df[predictors] = df[predictors]/df[predictors].max()
df.describe().transpose()

count      mean       std       min       25%       50%  \
sepal_length  150.0  0.739662  0.104818  0.544304  0.645570  0.734177   
sepal_width   150.0  0.694091  0.098544  0.454545  0.636364  0.681818   
petal_length  150.0  0.544734  0.255713  0.144928  0.231884  0.630435   
petal_width   150.0  0.479467  0.305264  0.040000  0.120000  0.520000   

                   75%  max  
sepal_length  0.810127  1.0  
sepal_width   0.750000  1.0  
petal_length  0.739130  1.0  
petal_width   0.720000  1.0

In [7]:
X = df[predictors].values
y = df[target_column].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=40)
print(X_train.shape); print(X_test.shape)

(120, 4)
(30, 4)


In [8]:
from sklearn.neural_network import MLPClassifier

In [52]:
mlp = MLPClassifier(hidden_layer_sizes=(4,4,4,4), activation='relu', solver='adam', max_iter=500)
mlp.fit(X_train,y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

c:\Users\ASUS\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
c:\Users\ASUS\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


In [101]:
mlp = MLPClassifier(hidden_layer_sizes=(4,6,12,6,4), activation='relu', solver='adam', max_iter=450)
mlp.fit(X_train,y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

c:\Users\ASUS\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
c:\Users\ASUS\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (450) reached and the optimization hasn't converged yet.
  warnings.warn(


In [62]:
X.shape

(150, 4)

In [103]:
predict_test_real = mlp.predict(X)


In [104]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[42  0  0]
 [ 0 35  3]
 [ 0  2 38]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        42
Iris-versicolor       0.95      0.92      0.93        38
 Iris-virginica       0.93      0.95      0.94        40

       accuracy                           0.96       120
      macro avg       0.96      0.96      0.96       120
   weighted avg       0.96      0.96      0.96       120



In [108]:
print(confusion_matrix(y,predict_test_real))
print(classification_report(y,predict_test_real))

[[50  0  0]
 [ 0 47  3]
 [ 0  2 48]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        50
Iris-versicolor       0.96      0.94      0.95        50
 Iris-virginica       0.94      0.96      0.95        50

       accuracy                           0.97       150
      macro avg       0.97      0.97      0.97       150
   weighted avg       0.97      0.97      0.97       150

